loop_on_end = true

[defaults]
format = "{time}\n"
time_format = "%M:%S"

[[sessions]]
id = "work"
name = "Work"
duration = "50m"
command = "notify-send --app-name uair --icon clock 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "10m"
command = "notify-send --app-name uair --icon clock 'Rest Done!'"
